apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: laas-api-tenant-$(TENANT_ID)
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/cloudsql-instances: "$(PROJECT_ID):$(REGION):laas-sql"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "20"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 500
      timeoutSeconds: 300
      containers:
        - image: $(REGION)-docker.pkg.dev/$(PROJECT_ID)/laas/laas-api-tenant:$(REVISION)
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
            - name: TENANT_ID
              value: $(TENANT_ID)
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: laas-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: laas-secrets
                  key: JWT_SECRET_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: laas-secrets
                  key: SECRET_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: laas-secrets
                  key: REDIS_URL
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: $(PROJECT_ID)
            - name: GOOGLE_CLOUD_REGION
              value: $(REGION)
            - name: CORS_ORIGINS
              value: "https://$(TENANT_ID).laas-platform.com,https://laas-frontend-$(PROJECT_ID).$(REGION).run.app"
            - name: ALLOWED_HOSTS
              value: "$(TENANT_ID).laas-platform.com,laas-api-tenant-$(TENANT_ID)-$(PROJECT_ID).$(REGION).run.app"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: laas-secrets
                  key: SENTRY_DSN
                  optional: true
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
