apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: laas-frontend
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "50"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
        - image: $(REGION)-docker.pkg.dev/$(PROJECT_ID)/laas/laas-frontend:$(REVISION)
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              value: production
            - name: NEXT_PUBLIC_API_URL
              value: "https://laas-api-core-$(PROJECT_ID).$(REGION).run.app"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://laas-frontend-$(PROJECT_ID).$(REGION).run.app"
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: $(PROJECT_ID)
            - name: GOOGLE_CLOUD_REGION
              value: $(REGION)
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
