version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laas_platform
      POSTGRES_USER: laas_user
      POSTGRES_PASSWORD: laas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laas_user -d laas_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LAAS API Application
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://laas_user:laas_password@postgres:5432/laas_platform
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=development-secret-key-change-in-production
      - DEBUG=true
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database Migration Service
  migrate:
    build:
      context: .
      target: development
    environment:
      - DATABASE_URL=postgresql://laas_user:laas_password@postgres:5432/laas_platform
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]
    profiles:
      - migration

volumes:
  postgres_data:
  redis_data:
