name: Database Migration

on:
  workflow_dispatch:
    inputs:
      migration_type:
        description: 'Type of migration to run'
        required: true
        default: 'upgrade'
        type: choice
        options:
        - upgrade
        - downgrade
        - reset
      target_revision:
        description: 'Target revision (for downgrade)'
        required: false
        type: string

env:
  PROJECT_ID: laas-platform-1758016737
  REGION: us-central1

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Database Migration
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Set up Cloud SQL Proxy
      uses: google-github-actions/setup-cloud-sql-proxy@v2
      with:
        cloud_sql_instance_connection_name: ${{ env.PROJECT_ID }}:${{ env.REGION }}:laas-sql
        port: 5432
        
    - name: Wait for Cloud SQL Proxy
      run: |
        for i in {1..30}; do
          if nc -z localhost 5432; then
            echo "Cloud SQL Proxy is ready"
            break
          fi
          echo "Waiting for Cloud SQL Proxy... ($i/30)"
          sleep 2
        done
        
    - name: Run database migration
      run: |
        export DATABASE_URL="postgresql://laas_user:${{ secrets.DB_PASSWORD }}@localhost:5432/laas_platform"
        
        if [ "${{ github.event.inputs.migration_type }}" = "upgrade" ]; then
          echo "Running database upgrade..."
          alembic upgrade head
        elif [ "${{ github.event.inputs.migration_type }}" = "downgrade" ]; then
          echo "Running database downgrade to ${{ github.event.inputs.target_revision }}..."
          alembic downgrade ${{ github.event.inputs.target_revision }}
        elif [ "${{ github.event.inputs.migration_type }}" = "reset" ]; then
          echo "Resetting database..."
          alembic downgrade base
          alembic upgrade head
        fi
        
    - name: Verify migration
      run: |
        export DATABASE_URL="postgresql://laas_user:${{ secrets.DB_PASSWORD }}@localhost:5432/laas_platform"
        alembic current
        alembic history