name: Manage Secrets

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'list'
        type: choice
        options:
        - list
        - create
        - update
        - delete
      secret_name:
        description: 'Secret name (for create/update/delete)'
        required: false
        type: string
      secret_value:
        description: 'Secret value (for create/update)'
        required: false
        type: string

env:
  PROJECT_ID: laas-platform-1758016737

jobs:
  manage-secrets:
    runs-on: ubuntu-latest
    name: Manage Google Cloud Secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Google Auth
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: List secrets
      if: github.event.inputs.action == 'list'
      run: |
        echo "📋 Current secrets in project:"
        gcloud secrets list --format="table(name,createTime,labels)"
        
    - name: Create secret
      if: github.event.inputs.action == 'create'
      run: |
        if [ -z "${{ github.event.inputs.secret_name }}" ] || [ -z "${{ github.event.inputs.secret_value }}" ]; then
          echo "❌ Error: Both secret_name and secret_value are required for create action"
          exit 1
        fi
        
        echo "Creating secret: ${{ github.event.inputs.secret_name }}"
        echo -n "${{ github.event.inputs.secret_value }}" | gcloud secrets create ${{ github.event.inputs.secret_name }} --data-file=-
        echo "✅ Secret created successfully"
        
    - name: Update secret
      if: github.event.inputs.action == 'update'
      run: |
        if [ -z "${{ github.event.inputs.secret_name }}" ] || [ -z "${{ github.event.inputs.secret_value }}" ]; then
          echo "❌ Error: Both secret_name and secret_value are required for update action"
          exit 1
        fi
        
        echo "Updating secret: ${{ github.event.inputs.secret_name }}"
        echo -n "${{ github.event.inputs.secret_value }}" | gcloud secrets versions add ${{ github.event.inputs.secret_name }} --data-file=-
        echo "✅ Secret updated successfully"
        
    - name: Delete secret
      if: github.event.inputs.action == 'delete'
      run: |
        if [ -z "${{ github.event.inputs.secret_name }}" ]; then
          echo "❌ Error: secret_name is required for delete action"
          exit 1
        fi
        
        echo "Deleting secret: ${{ github.event.inputs.secret_name }}"
        gcloud secrets delete ${{ github.event.inputs.secret_name }} --quiet
        echo "✅ Secret deleted successfully"

